// 500+ Google Font families for the text font picker.
// Loaded lazily (on scroll) by FontPanel via the Google Fonts CSS API.
export const GOOGLE_FONTS = [
  'Roboto', 'Open Sans', 'Lato', 'Montserrat', 'Oswald', 'Raleway', 'Poppins', 'Merriweather',
  'Nunito', 'Playfair Display', 'Roboto Condensed', 'Ubuntu', 'Roboto Slab', 'PT Sans', 'Lora',
  'Noto Sans', 'Rubik', 'Work Sans', 'Mukta', 'Roboto Mono', 'Nanum Gothic', 'Fira Sans',
  'Quicksand', 'Inter', 'Karla', 'Barlow', 'Josefin Sans', 'Inconsolata', 'Arimo', 'PT Serif',
  'Dosis', 'Libre Baskerville', 'Bitter', 'Cabin', 'Anton', 'Source Sans Pro', 'Titillium Web',
  'Heebo', 'Nanum Myeongjo', 'Hind', 'Crimson Text', 'Bebas Neue', 'Abel', 'Teko', 'Exo 2',
  'Pacifico', 'Dancing Script', 'Shadows Into Light', 'Indie Flower', 'Lobster', 'Caveat',
  'Comfortaa', 'Satisfy', 'Great Vibes', 'Sacramento', 'Permanent Marker', 'Amatic SC',
  'Courgette', 'Kaushan Script', 'Cookie', 'Yellowtail', 'Pinyon Script', 'Tangerine',
  'Allura', 'Marck Script', 'Homemade Apple', 'Rock Salt', 'Gloria Hallelujah', 'Bangers',
  'Fredoka One', 'Righteous', 'Luckiest Guy', 'Lilita One', 'Baloo 2', 'Chewy', 'Titan One',
  'Bungee', 'Monoton', 'Alfa Slab One', 'Passion One', 'Fugaz One', 'Russo One', 'Staatliches',
  'Shrikhand', 'Ultra', 'Bowlby One', 'Bowlby One SC', 'Black Ops One', 'Creepster', 'Nosifer',
  'Eater', 'Frijole', 'Metamorphous', 'Cinzel', 'Cinzel Decorative', 'Marcellus', 'Forum',
  'Cormorant Garamond', 'EB Garamond', 'Spectral', 'Vollkorn', 'Domine', 'Arvo', 'Rokkitt',
  'Zilla Slab', 'Slabo 27px', 'Aleo', 'Bree Serif', 'Crete Round', 'Old Standard TT',
  'Cardo', 'Sorts Mill Goudy', 'Gentium Book Basic', 'Noto Serif', 'Source Serif Pro',
  'Frank Ruhl Libre', 'Alegreya', 'Alegreya Sans', 'Cormorant', 'Prata', 'Della Respira',
  'Abril Fatface', 'Yeseva One', 'Playfair Display SC', 'Rozha One', 'Gilda Display',
  'Italiana', 'Marcellus SC', 'Cormorant SC', 'Holtwood One SC', 'Rufina', 'Bodoni Moda',
  'DM Sans', 'DM Serif Display', 'DM Serif Text', 'Manrope', 'Sora', 'Epilogue', 'Space Grotesk',
  'Space Mono', 'Outfit', 'Lexend', 'Plus Jakarta Sans', 'Figtree', 'Onest', 'Schibsted Grotesk',
  'Archivo', 'Archivo Black', 'Archivo Narrow', 'Saira', 'Saira Condensed', 'Khand', 'Rajdhani',
  'Kanit', 'Sarabun', 'Prompt', 'Mitr', 'Chakra Petch', 'Bai Jamjuree', 'IBM Plex Sans',
  'IBM Plex Serif', 'IBM Plex Mono', 'Jost', 'Red Hat Display', 'Red Hat Text', 'Be Vietnam Pro',
  'Hanken Grotesk', 'Albert Sans', 'Bricolage Grotesque', 'Instrument Sans', 'Instrument Serif',
  'Fraunces', 'Newsreader', 'Literata', 'Petrona', 'Piazzolla', 'STIX Two Text', 'Crimson Pro',
  'Besley', 'Yrsa', 'Zilla Slab Highlight', 'Bevan', 'Patua One', 'Coustard', 'Sansita',
  'Acme', 'Alata', 'Antic', 'Antic Slab', 'Asap', 'Asap Condensed', 'Assistant', 'Average',
  'Average Sans', 'Bai Jamjuree', 'Balsamiq Sans', 'Basic', 'Belleza', 'BenchNine', 'Biryani',
  'Cabin Condensed', 'Cantarell', 'Cantata One', 'Catamaran', 'Caudex', 'Chivo', 'Coda',
  'Convergence', 'Cuprum', 'David Libre', 'Didact Gothic', 'Economica', 'El Messiri', 'Encode Sans',
  'Engagement', 'Englebert', 'Enriqueta', 'Esteban', 'Fjalla One', 'Francois One', 'Gelasio',
  'Glegoo', 'Gothic A1', 'Gudea', 'Hammersmith One', 'Hind Madurai', 'Hind Siliguri', 'Hind Vadodara',
  'Imprima', 'Inder', 'Istok Web', 'Jaldi', 'Jura', 'Kameron', 'Khula', 'Kreon', 'Kumbh Sans',
  'Ledger', 'Lekton', 'Libre Franklin', 'Maven Pro', 'Merriweather Sans', 'Metrophobic',
  'Michroma', 'Montserrat Alternates', 'Mada', 'Mallanna', 'Marmelad', 'Martel', 'Martel Sans',
  'Marvel', 'Mate', 'Mate SC', 'Meera Inimai', 'Mada', 'Molengo', 'Mada', 'Mukta Malar',
  'Mukta Vaani', 'Nanum Gothic Coding', 'Newsreader', 'Nobile', 'Numans', 'Nunito Sans',
  'Overpass', 'Overpass Mono', 'Oxygen', 'Pathway Gothic One', 'Pavanam', 'Philosopher',
  'Play', 'Pontano Sans', 'Pragati Narrow', 'Prociono', 'Proza Libre', 'PT Sans Caption',
  'PT Sans Narrow', 'Puritan', 'Quattrocento', 'Quattrocento Sans', 'Questrial', 'Quicksand',
  'Radio Canada', 'Ramabhadra', 'Rambla', 'Rasa', 'Readex Pro', 'Reem Kufi', 'Rhodium Libre',
  'Ruda', 'Ruluko', 'Rum Raisin', 'Saira Semi Condensed', 'Sarala', 'Scada', 'Scheherazade New',
  'Secular One', 'Sen', 'Shanti', 'Signika', 'Signika Negative', 'Sintony', 'Snippet', 'Solway',
  'Spinnaker', 'Strait', 'Sumana', 'Sunflower', 'Syne', 'Tajawal', 'Telex', 'Tenor Sans',
  'Texturina', 'Thasadith', 'Tienne', 'Tinos', 'Tomorrow', 'Trirong', 'Trispace', 'Trocchi',
  'Trykker', 'Unna', 'Urbanist', 'Varela', 'Varela Round', 'Varta', 'Vesper Libre', 'Viga',
  'Voces', 'Volkhov', 'Vollkorn SC', 'Vazirmatn', 'Wix Madefor Display', 'Wix Madefor Text',
  'Yaldevi', 'Yantramanav', 'Yatra One', 'Zen Kaku Gothic New', 'Zen Maru Gothic',
  'Zen Old Mincho', 'Allerta', 'Allerta Stencil', 'Allison', 'Almendra', 'Almendra SC',
  'Amarante', 'Amaranth', 'Amita', 'Andada Pro', 'Andika', 'Angkor', 'Annie Use Your Telescope',
  'Anonymous Pro', 'Architects Daughter', 'Aref Ruqaa', 'Arsenal', 'Artifika', 'Atma',
  'Atomic Age', 'Aubrey', 'Audiowide', 'Autour One', 'Aclonica', 'Akronim', 'Aladin',
  'Aldrich', 'Alegreya Sans SC', 'Alex Brush', 'Alfa Slab One', 'Allan', 'Almarai',
  'Amethysta', 'Amiko', 'Amiri', 'Anaheim', 'Andale Mono', ' Animation', 'Antonio', 'Anybody',
  'Aoboshi One', 'Arapey', 'Arbutus', 'Arbutus Slab', 'Arizonia', 'Armata', 'Arya', 'Asar',
  'Asset', 'Astloch', 'Asul', 'Athiti', 'Atomic Age', 'Aubrey', 'Azeret Mono', 'B612',
  'B612 Mono', 'Bacasime Antique', 'Bahiana', 'Bahianita', 'Bakbak One', 'Ballet', 'Baloo Bhai 2',
  'Baloo Bhaijaan 2', 'Baloo Bhaina 2', 'Baloo Chettan 2', 'Baloo Da 2', 'Baloo Paaji 2',
  'Baloo Tamma 2', 'Baloo Tammudu 2', 'Baloo Thambi 2', 'Balthazar', 'Bangers', 'Barlow Condensed',
  'Barlow Semi Condensed', 'Barriecito', 'Barrio', 'Battambang', 'Baumans', 'Bayon',
  'Be Vietnam', 'Beau Rivage', 'Bellefair', 'Belgrano', 'Bellota', 'Bellota Text', 'Benne',
  'Bentham', 'Berkshire Swash', 'Beth Ellen', 'Big Shoulders Display', 'Big Shoulders Text',
  'Bigelow Rules', 'Bigshot One', 'Bilbo', 'Bilbo Swash Caps', 'BioRhyme', 'Birthstone',
  'Birthstone Bounce', 'Biryani', 'Bizcochito', 'Blaka', 'Blaka Hollow', 'Blinker',
  'Bodoni Moda SC', 'Bokor', 'Boldonse', 'Bona Nova', 'Bonbon', 'Bonheur Royale', 'Boogaloo',
  'Borel', 'Bricolage Grotesque', 'Brawler', 'Bruno Ace', 'Bruno Ace SC', 'Brygada 1918',
  'Bubblegum Sans', 'Bubbler One', 'Buda', 'Buenard', 'Bungee Hairline', 'Bungee Inline',
  'Bungee Outline', 'Bungee Shade', 'Bungee Spice', 'Butcherman', 'Butterfly Kids', 'Cabin Sketch',
  'Caesar Dressing', 'Cagliostro', 'Cairo', 'Caladea', 'Calistoga', 'Calligraffitti', 'Cambay',
  'Cambo', 'Candal', 'Cantarell', 'Caprasimo', 'Capriola', 'Caramel', 'Carattere', 'Cardo',
  'Carlito', 'Carme', 'Carrois Gothic', 'Carter One', 'Castoro', 'Catamaran', 'Caveat Brush',
  'Cedarville Cursive', 'Ceviche One', 'Chakra Petch', 'Changa', 'Changa One', 'Chango',
  'Charm', 'Charmonman', 'Chathura', 'Chau Philomene One', 'Chela One', 'Chelsea Market',
  'Chenla', 'Cherish', 'Cherry Cream Soda', 'Cherry Swash', 'Chicle', 'Chilanka', 'Chocolate Classical Sans',
  'Chonburi', 'Cinzel', 'Clicker Script', 'Coda Caption', 'Codystar', 'Coiny', 'Combo',
  'Comforter', 'Comforter Brush', 'Comic Neue', 'Coming Soon', 'Comme', 'Concert One', 'Condiment',
  'Content', 'Contrail One', 'Cookie', 'Copse', 'Corben', 'Corinthia', 'Cormorant Infant',
  'Cormorant Unicase', 'Cormorant Upright', 'Courier Prime', 'Cousine', 'Coustard', 'Covered By Your Grace',
  'Crafty Girls', 'Creepster', 'Crete Round', 'Croissant One', 'Crushed', 'Cuprum', 'Cute Font',
  'Cutive', 'Cutive Mono', 'DM Mono', 'Dai Banna SIL', 'Damion', 'Dancing Script', 'Dangrek',
  'Darker Grotesque', 'Darumadrop One', 'David Libre', 'Dawning of a New Day', 'Days One',
  'Dekko', 'Dela Gothic One', 'Delius', 'Delius Swash Caps', 'Delius Unicase', 'Della Respira',
  'Denk One', 'Devonshire', 'Dhurjati', 'Diplomata', 'Diplomata SC', 'Doppio One', 'Dorsa',
  'Dosis', 'DotGothic16', 'Dr Sugiyama', 'Duru Sans', 'DynaPuff', 'Dynalight', 'Eagle Lake',
  'East Sea Dokdo', 'Eater', 'Economica', 'Eczar', 'Edu NSW ACT Foundation', 'El Messiri',
  'Electrolize', 'Elsie', 'Elsie Swash Caps', 'Emblema One', 'Emilys Candy', 'Encode Sans Condensed',
  'Encode Sans Expanded', 'Engagement', 'Englebert', 'Enriqueta', 'Ephesis', 'Epilogue',
  'Erica One', 'Esteban', 'Estonia', 'Euphoria Script', 'Ewert', 'Exo', 'Expletus Sans',
  'Explora', 'Fahkwang', 'Familjen Grotesk', 'Fanwood Text', 'Farro', 'Farsan', 'Fascinate',
  'Fascinate Inline', 'Faster One', 'Fasthand', 'Fauna One', 'Faustina', 'Federant', 'Federo',
  'Felipa', 'Fenix', 'Festive', 'Figtree', 'Finger Paint', 'Finlandica', 'Fira Code', 'Fira Mono',
  'Fjord One', 'Flamenco', 'Flavors', 'Fleur De Leah', 'Flow Block', 'Flow Circular', 'Flow Rounded',
  'Foldit', 'Fondamento', 'Fontdiner Swanky', 'Forum', 'Fragment Mono', 'Francois One', 'Frank Ruhl Libre',
  'Fraunces', 'Freckle Face', 'Fredericka the Great', 'Freehand', 'Fresca', 'Frijole', 'Fruktur',
  'Fugaz One', 'Fuggles', 'Fuzzy Bubbles', 'GFS Didot', 'GFS Neohellenic', 'Gabarito', 'Gabriela',
  'Gaegu', 'Gafata', 'Gajraj One', 'Galada', 'Galdeano', 'Galindo', 'Gamja Flower', 'Gantari',
  'Gasoek One', 'Gayathri', 'Geist', 'Geist Mono', 'Gelasio', 'Gemunu Libre', 'Genos', 'Gentium Plus',
  'Geo', 'Geologica', 'Georama', 'Geostar', 'Geostar Fill', 'Germania One', 'Gideon Roman',
  'Gidugu', 'Gilda Display', 'Girassol', 'Give You Glory', 'Glass Antiqua', 'Glegoo', 'Gluten',
  'Goblin One', 'Gochi Hand', 'Goldman', 'Golos Text', 'Gorditas', 'Gothic A1', 'Gotu', 'Goudy Bookletter 1911',
  'Gowun Batang', 'Gowun Dodum', 'Graduate', 'Grand Hotel', 'Grandiflora One', 'Grandstander',
  'Grape Nuts', 'Gravitas One', 'Great Vibes', 'Grechen Fuemen', 'Grenze', 'Grenze Gotisch',
  'Grey Qo', 'Griffy', 'Gruppo', 'Gudea', 'Gugi', 'Gulzar', 'Gupter', 'Gurajada', 'Gwendolyn',
  'Habibi', 'Hachi Maru Pop', 'Hahmlet', 'Halant', 'Hammersmith One', 'Hanalei', 'Hanalei Fill',
  'Handlee', 'Hanken Grotesk', 'Hanuman', 'Happy Monkey', 'Harmattan', 'Headland One', 'Hedvig Letters Sans',
  'Hedvig Letters Serif', 'Heebo', 'Henny Penny', 'Hepta Slab', 'Herr Von Muellerhoff', 'Hi Melody',
  'Hina Mincho', 'Hind', 'Holtwood One SC', 'Homemade Apple', 'Homenaje', 'Honk', 'Hubballi',
  'Hurricane', 'IBM Plex Sans Condensed', 'IM Fell DW Pica', 'IM Fell English', 'Iansui', 'Ibarra Real Nova',
  'Iceberg', 'Iceland', 'Imbue', 'Imperial Script', 'Imprima', 'Inclusive Sans', 'Inconsolata',
  'Inder', 'Indie Flower', 'Ingrid Darling', 'Inika', 'Inknut Antiqua', 'Inria Sans', 'Inria Serif',
  'Inspiration', 'Instrument Sans', 'Inter Tight', 'Irish Grover', 'Island Moments', 'Istok Web',
  'Italianno', 'Itim', 'Jacquard 12', 'Jacquarda Bastarda 9', 'Jacques Francois', 'Jaini',
  'Jaldi', 'Jaro', 'Jersey 10', 'Jersey 15', 'Jersey 20', 'Jersey 25', 'JetBrains Mono',
  'Jim Nightshade', 'Joan', 'Jockey One', 'Jolly Lodger', 'Jomhuria', 'Jomolhari', 'Josefin Slab',
  'Joti One', 'Jua', 'Judson', 'Julee', 'Julius Sans One', 'Junge', 'Jura', 'Just Another Hand',
  'Just Me Again Down Here', 'K2D', 'Kablammo', 'Kadwa', 'Kaisei Decol', 'Kaisei HarunoUmi',
  'Kaisei Opti', 'Kaisei Tokumin', 'Kalam', 'Kalnia', 'Kameron', 'Kanit', 'Kantumruy Pro',
  'Karantina', 'Karla', 'Karma', 'Katibeh', 'Kaushan Script', 'Kavivanar', 'Kavoon', 'Kdam Thmor Pro',
  'Keania One', 'Kelly Slab', 'Kenia', 'Khand', 'Khmer', 'Khula', 'Kings', 'Kirang Haerang',
  'Kite One', 'Kiwi Maru', 'Klee One', 'Knewave', 'KoHo', 'Kodchasan', 'Kode Mono', 'Koh Santepheap',
  'Kolker Brush', 'Konkhmer Sleokchher', 'Kosugi', 'Kosugi Maru', 'Kotta One', 'Koulen', 'Kranky',
  'Kreon', 'Kristi', 'Krona One', 'Krub', 'Kufam', 'Kulim Park', 'Kumar One', 'Kumbh Sans',
  'Kurale', 'La Belle Aurore', 'Labrada', 'Lacquer', 'Laila', 'Lakki Reddy', 'Lalezar', 'Lancelot',
  'Langar', 'Lateef', 'Lato', 'League Gothic', 'League Script', 'League Spartan', 'Leckerli One',
  'Ledger', 'Lekton', 'Lemon', 'Lemonada', 'Lexend Deca', 'Lexend Giga', 'Libre Barcode 39',
  'Libre Bodoni', 'Libre Caslon Display', 'Libre Caslon Text', 'Licorice', 'Life Savers',
  'Lilita One', 'Lily Script One', 'Limelight', 'Linden Hill', 'Linefont', 'Lisu Bosa', 'Literata',
  'Liu Jian Mao Cao', 'Livvic', 'Lobster Two', 'Londrina Outline', 'Londrina Shadow', 'Londrina Sketch',
  'Londrina Solid', 'Long Cang', 'Lora', 'Love Light', 'Love Ya Like A Sister', 'Loved by the King',
  'Lovers Quarrel', 'Luckiest Guy', 'Lugrasimo', 'Lumanosimo', 'Lunasima', 'Lusitana', 'Lustria',
  'Luxurious Roman', 'Luxurious Script', 'M PLUS 1', 'M PLUS 1 Code', 'M PLUS 1p', 'M PLUS 2',
  'M PLUS Rounded 1c', 'Ma Shan Zheng', 'Macondo', 'Macondo Swash Caps', 'Mada', 'Madimi One',
  'Magra', 'Maiden Orange', 'Maitree', 'Major Mono Display', 'Mako', 'Mali', 'Mallanna', 'Maname',
  'Mandali', 'Manjari', 'Manrope', 'Mansalva', 'Manuale', 'Marcellus', 'Marck Script', 'Margarine',
  'Marhey', 'Markazi Text', 'Marko One', 'Marmelad', 'Martel', 'Martian Mono', 'Marvel', 'Mate',
  'Maven Pro', 'McLaren', 'Mea Culpa', 'Meddon', 'MedievalSharp', 'Medula One', 'Meera Inimai',
  'Megrim', 'Meie Script', 'Meow Script', 'Merienda', 'Merriweather', 'Metal', 'Metal Mania',
  'Metamorphous', 'Metrophobic', 'Michroma', 'Micro 5', 'Milonga', 'Miltonian', 'Mina', 'Mingzat',
  'Miniver', 'Miriam Libre', 'Mirza', 'Miss Fajardose', 'Mitr', 'Mochiy Pop One', 'Modak',
  'Modern Antiqua', 'Mogra', 'Mohave', 'Moirai One', 'Molengo', 'Molle', 'Monda', 'Monofett',
  'Monomaniac One', 'Monoton', 'Monsieur La Doulaise', 'Montaga', 'Montagu Slab', 'Montez',
  'Montserrat Subrayada', 'Moo Lah Lah', 'Mooli', 'Moon Dance', 'Moul', 'Moulpali', 'Mountains of Christmas',
  'Mouse Memoirs', 'Mr Bedfort', 'Mr Dafoe', 'Mr De Haviland', 'Mrs Saint Delafield', 'Mrs Sheppards',
  'Ms Madi', 'Mukta', 'Mulish', 'Murecho', 'MuseoModerno', 'My Soul', 'Mynerve', 'Mystery Quest',
  'Nabla', 'Namdhinggo', 'Nanum Brush Script', 'Nanum Pen Script', 'Narnoor', 'Neonderthaw',
  'Nerko One', 'Neucha', 'Neuton', 'New Rocker', 'New Tegomin', 'News Cycle', 'Newsreader',
  'Niconne', 'Niramit', 'Nixie One', 'Nobile', 'Nokora', 'Norican', 'Nosifer', 'Notable',
  'Nothing You Could Do', 'Noticia Text', 'Noto Color Emoji', 'Noto Sans Display', 'Noto Sans Mono',
  'Noto Serif Display', 'Nova Cut', 'Nova Flat', 'Nova Mono', 'Nova Oval', 'Nova Round', 'Nova Script',
  'Nova Slim', 'Nova Square', 'Numans', 'Nunito', 'Nuosu SIL', 'Odibee Sans', 'Odor Mean Chey',
  'Offside', 'Oi', 'Ojuju', 'Old Standard TT', 'Oldenburg', 'Ole', 'Oleo Script', 'Oleo Script Swash Caps',
  'Onest', 'Oooh Baby', 'Open Sans', 'Oranienbaum', 'Orbit', 'Orbitron', 'Oregano', 'Orelega One',
  'Orienta', 'Original Surfer', 'Oswald', 'Outfit', 'Over the Rainbow', 'Overlock', 'Overlock SC',
  'Overpass', 'Ovo', 'Oxanium', 'Oxygen', 'Oxygen Mono', 'PT Mono', 'PT Sans', 'PT Serif Caption',
  'Pacifico', 'Padauk', 'Padyakke Expanded One', 'Palanquin', 'Palanquin Dark', 'Palette Mosaic',
  'Pangolin', 'Paprika', 'Parisienne', 'Passero One', 'Passion One', 'Passions Conflict', 'Pathway Extreme',
  'Pathway Gothic One', 'Patrick Hand', 'Patrick Hand SC', 'Pattaya', 'Patua One', 'Pavanam',
  'Paytone One', 'Peddana', 'Peralta', 'Permanent Marker', 'Petemoss', 'Petit Formal Script',
  'Petrona', 'Philosopher', 'Phudu', 'Piazzolla', 'Piedra', 'Pinyon Script', 'Pirata One',
  'Pixelify Sans', 'Plaster', 'Platypi', 'Play', 'Playball', 'Playfair', 'Playpen Sans',
  'Playwrite AR', 'Plus Jakarta Sans', 'Pochaevsk', 'Podkova', 'Poetsen One', 'Poiret One',
  'Poller One', 'Poltawski Nowy', 'Poly', 'Pompiere', 'Pontano Sans', 'Poor Story', 'Poppins',
  'Port Lligat Sans', 'Port Lligat Slab', 'Potta One', 'Pragati Narrow', 'Praise', 'Prata',
  'Preahvihear', 'Press Start 2P', 'Pridi', 'Princess Sofia', 'Prociono', 'Prompt', 'Prosto One',
  'Protest Guerrilla', 'Protest Revolution', 'Protest Riot', 'Protest Strike', 'Proza Libre',
  'Public Sans', 'Puppies Play', 'Puritan', 'Purple Purse', 'Qahiri', 'Quando', 'Quantico',
  'Quattrocento', 'Quattrocento Sans', 'Questrial', 'Quicksand', 'Quintessential', 'Qwigley',
  'Qwitcher Grypen', 'REM', 'Racing Sans One', 'Radio Canada', 'Radley', 'Raleway', 'Raleway Dots',
  'Ramabhadra', 'Ramaraja', 'Rambla', 'Rammetto One', 'Rampart One', 'Ranchers', 'Rancho', 'Ranga',
  'Rajdhani', 'Rakkas', 'Raleway', 'Ramaraja', 'Rasa', 'Rationale', 'Ravi Prakash', 'Readex Pro',
  'Recursive', 'Red Hat Display', 'Red Hat Mono', 'Red Hat Text', 'Red Rose', 'Redacted', 'Redacted Script',
  'Redressed', 'Reem Kufi', 'Reenie Beanie', 'Reggae One', 'Rethink Sans', 'Revalia', 'Rhodium Libre',
  'Ribeye', 'Ribeye Marrow', 'Righteous', 'Risque', 'Roboto', 'Roboto Condensed', 'Roboto Flex',
  'Roboto Mono', 'Roboto Serif', 'Roboto Slab', 'Rochester', 'Rock 3D', 'Rock Salt', 'RocknRoll One',
  'Rokkitt', 'Romanesco', 'Ropa Sans', 'Rosario', 'Rosarivo', 'Rouge Script', 'Rowdies', 'Rozha One',
  'Rubik', 'Rubik Bubbles', 'Rubik Dirt', 'Rubik Glitch', 'Rubik Iso', 'Rubik Marker Hatch',
  'Rubik Mono One', 'Rubik Moonrocks', 'Rubik Pixels', 'Rubik Puddles', 'Rubik Wet Paint',
  'Ruda', 'Rufina', 'Ruge Boogie', 'Ruluko', 'Rum Raisin', 'Ruslan Display', 'Russo One',
  'Ruthie', 'Ruwudu', 'Rye', 'STIX Two Text', 'Sacramento', 'Sahitya', 'Sail', 'Saira',
  'Saira Condensed', 'Saira Extra Condensed', 'Saira Semi Condensed', 'Saira Stencil One',
  'Salsa', 'Sanchez', 'Sancreek', 'Sankofa Display', 'Sansita', 'Sansita Swashed', 'Sarabun',
  'Sarala', 'Sarina', 'Sarpanch', 'Sassy Frass', 'Satisfy', 'Sawarabi Gothic', 'Sawarabi Mincho',
  'Scada', 'Scheherazade New', 'Schibsted Grotesk', 'Schoolbell', 'Scope One', 'Seaweed Script',
  'Secular One', 'Sedan', 'Sedan SC', 'Sedgwick Ave', 'Sedgwick Ave Display', 'Sen', 'Send Flowers',
  'Sevillana', 'Seymour One', 'Shadows Into Light', 'Shadows Into Light Two', 'Shalimar', 'Shantell Sans',
  'Shanti', 'Share', 'Share Tech', 'Share Tech Mono', 'Shippori Antique', 'Shippori Mincho',
  'Shizuru', 'Shojumaru', 'Short Stack', 'Shrikhand', 'Siemreap', 'Sigmar', 'Sigmar One',
  'Signika', 'Silkscreen', 'Simonetta', 'Single Day', 'Sintony', 'Sirin Stencil', 'Six Caps',
  'Skranji', 'Slabo 13px', 'Slabo 27px', 'Slackey', 'Smokum', 'Smooch', 'Smooch Sans', 'Smythe',
  'Sniglet', 'Snippet', 'Snowburst One', 'Sofadi One', 'Sofia', 'Sofia Sans', 'Solitreo', 'Solway',
  'Sometype Mono', 'Song Myung', 'Sono', 'Sonsie One', 'Sora', 'Sorts Mill Goudy', 'Source Code Pro',
  'Source Sans 3', 'Source Serif 4', 'Space Grotesk', 'Space Mono', 'Special Elite', 'Spectral',
  'Spectral SC', 'Spicy Rice', 'Spinnaker', 'Spirax', 'Splash', 'Spline Sans', 'Spline Sans Mono',
  'Squada One', 'Square Peg', 'Sree Krushnadevaraya', 'Sriracha', 'Srisakdi', 'Staatliches',
  'Stalemate', 'Stalinist One', 'Stardos Stencil', 'Stick', 'Stick No Bills', 'Stint Ultra Condensed',
  'Stint Ultra Expanded', 'Stoke', 'Strait', 'Style Script', 'Stylish', 'Sue Ellen Francisco',
  'Suez One', 'Sulphur Point', 'Sumana', 'Sunflower', 'Sunshiney', 'Supermercado One', 'Sura',
  'Suranna', 'Suravaram', 'Suwannaphum', 'Swanky and Moo Moo', 'Syncopate', 'Syne', 'Syne Mono',
  'Syne Tactile', 'Tac One', 'Tagesschrift', 'Tai Heritage Pro', 'Tajawal', 'Tangerine', 'Tapestry',
  'Taprom', 'Tauri', 'Taviraj', 'Teachers', 'Teko', 'Tektur', 'Telex', 'Tenali Ramakrishna',
  'Tenor Sans', 'Text Me One', 'Texturina', 'Thasadith', 'The Girl Next Door', 'The Nautigal',
  'Tienne', 'Tillana', 'Tilt Neon', 'Tilt Prism', 'Tilt Warp', 'Timmana', 'Tinos', 'Tiny5',
  'Tiro Bangla', 'Tiro Devanagari Hindi', 'Tiro Gurmukhi', 'Tiro Kannada', 'Tiro Tamil', 'Tiro Telugu',
  'Titan One', 'Titillium Web', 'Tomorrow', 'Tourney', 'Trade Winds', 'Train One', 'Trirong',
  'Trispace', 'Trocchi', 'Trochut', 'Truculenta', 'Trykker', 'Tsukimi Rounded', 'Tulpen One',
  'Turret Road', 'Twinkle Star', 'Ubuntu', 'Ubuntu Condensed', 'Ubuntu Mono', 'Ubuntu Sans',
  'Uchen', 'Ultra', 'Unbounded', 'Uncial Antiqua', 'Underdog', 'Unica One', 'UnifrakturCook',
  'UnifrakturMaguntia', 'Unkempt', 'Unlock', 'Unna', 'Updock', 'Urbanist', 'VT323', 'Vampiro One',
  'Varela', 'Varela Round', 'Varta', 'Vast Shadow', 'Vazirmatn', 'Vesper Libre', 'Viaoda Libre',
  'Vibes', 'Vibur', 'Victor Mono', 'Vidaloka', 'Viga', 'Vina Sans', 'Voces', 'Volkhov', 'Vollkorn',
  'Vollkorn SC', 'Voltaire', 'Vujahday Script', 'Waiting for the Sunrise', 'Wallpoet', 'Walter Turncoat',
  'Warnes', 'Water Brush', 'Waterfall', 'Wavefont', 'Wellfleet', 'Wendy One', 'Whisper', 'WindSong',
  'Wire One', 'Wittgenstein', 'Wix Madefor Display', 'Wix Madefor Text', 'Work Sans', 'Workbench',
  'Xanh Mono', 'Yaldevi', 'Yanone Kaffeesatz', 'Yantramanav', 'Yatra One', 'Yellowtail', 'Yeon Sung',
  'Yeseva One', 'Yesteryear', 'Yomogi', 'Young Serif', 'Yrsa', 'Ysabeau', 'Ysabeau Infant',
  'Ysabeau Office', 'Ysabeau SC', 'Yuji Boku', 'Yuji Hentaigana Akari', 'Yuji Hentaigana Akebono',
  'Yuji Mai', 'Yuji Syuku', 'Yusei Magic', 'Zen Antique', 'Zen Antique Soft', 'Zen Dots',
  'Zen Kaku Gothic Antique', 'Zen Kaku Gothic New', 'Zen Kurenaido', 'Zen Loop', 'Zen Maru Gothic',
  'Zen Old Mincho', 'Zen Tokyo Zoo', 'Zeyada', 'Zhi Mang Xing', 'Zilla Slab', 'Zilla Slab Highlight',
]
